---
server:
  port: 8888
security:
  basic:
    enabled: true
  user:
    name: test
    password: test
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/iaforek/spring-cloudconfig-properties
          search-paths:
          - 'station*'
          repos:
            perf:
              pattern: 
                - "*/perf"
              uri: https://github.com/iaforek/spring-cloudconfig-properties-perf
              search-paths:
                - 'station*'